name: Check

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:
      - name: 'Install u-boot-tools'
        run: |
          sudo apt update
          sudo apt install -y u-boot-tools

      - name: 'Install Build Dependencies'
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y binutils git make bc bison openssl curl zip kmod cpio flex libelf-dev libssl-dev libtfm-dev libc6-dev device-tree-compiler ca-certificates python3 xz-utils libc6-dev aria2 build-essential ccache

      - name: 'Set Up Swap'
        run: |
          export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
          sudo swapoff $SWAP_FILE
          sudo rm -v $SWAP_FILE
          sudo fallocate -l 16G $SWAP_FILE
          sudo chmod 600 -v $SWAP_FILE
          sudo mkswap $SWAP_FILE
          sudo swapon $SWAP_FILE

      - name: 'Download GCC Toolchains'
        run: |
          mkdir -p $HOME/gcc-64 $HOME/gcc-32
          aria2c -o gcc-aarch64.tar.xz https://sources.buildroot.net/toolchain-external-arm-aarch64/gcc-arm-11.2-2022.02-x86_64-aarch64-none-linux-gnu.tar.xz
          tar -C $HOME/gcc-64 -xf gcc-aarch64.tar.xz
          aria2c -o gcc-arm.tar.xz https://github.com/armbian/mirror/releases/download/_toolchain/gcc-arm-11.2-2022.02-x86_64-arm-none-linux-gnueabihf.tar.xz
          tar -C $HOME/gcc-32 -xf gcc-arm.tar.xz

      - name: 'Clone Kernel Source'
        run: |
          git clone --recursive https://github.com/bet4it/linux-orangepi -b orange-pi-5.10-rk3588 kernel

      - name: 'Build Kernel'
        run: |
          cd kernel
          mkdir out -p -v
          export PATH=$HOME/gcc-64/bin:$HOME/gcc-32/bin:$PATH
          make -j$(nproc --all) linux_opsrc_rk3588_defconfig ARCH=arm64 all O=out
          make -j$(nproc --all) linux_opsrc_rk3588_defconfig ARCH=arm64 CROSS_COMPILE=aarch64-none-linux-gnu- CROSS_COMPILE_ARM32=arm-none-linux-gnueabihf- all O=out

      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: kernel-built-bootimg
          path: kernel/out/arch/arm64/boot/
          if-no-files-found: error
          overwrite: true
