name: Check

on:
  push:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:
      - name: 'Install u-boot-tools'
        run: |
          sudo apt update
          sudo apt install -y u-boot-tools

      - name: 'Install Build Dependencies'
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y binutils git make bc bison openssl curl zip kmod cpio flex libelf-dev libssl-dev libtfm-dev libc6-dev device-tree-compiler ca-certificates python3 xz-utils libc6-dev aria2 build-essential ccache

      - name: 'Download GCC Toolchains'
        run: |
          mkdir -p $HOME/gcc-64
          aria2c -o gcc-aarch64.tar.xz https://sources.buildroot.net/toolchain-external-arm-aarch64/gcc-arm-11.2-2022.02-x86_64-aarch64-none-linux-gnu.tar.xz
          tar -C $HOME/gcc-64 --strip-components=1 -xf gcc-aarch64.tar.xz

      - name: 'Clone Kernel Source'
        run: |
          git clone --depth=1 --recursive https://github.com/bet4it/linux-orangepi -b orange-pi-5.10-rk3588 kernel

      - name: 'Build Kernel'
        run: |
          cd kernel
          mkdir out -p -v
          export PATH=$HOME/gcc-64/bin:$PATH
          make ARCH=arm64 linux_opsrc_rk3588_defconfig O=out
          make -j$(nproc --all) ARCH=arm64 CROSS_COMPILE=aarch64-none-linux-gnu- Image O=out

      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: kernel-built-bootimg
          path: kernel/out/arch/arm64/boot/
          if-no-files-found: error
          overwrite: true
